# Generated by Django 5.0.6 on 2024-12-14 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0002_create_exams'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('EVALUETED', 'Evalueted')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('exam_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='answer.examanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('selected_alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.alternative')),
            ],
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['student', 'exam'], name='answer_exam_student_30c465_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('student', 'exam')},
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['exam_response', 'question'], name='answer_ques_exam_re_11c7d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('exam_response', 'question')},
        ),
    ]
