# Generated by Django 5.0.6 on 2024-12-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('EVALUETED', 'Evaluated')], default='PENDING', max_length=20),
        ),
    ]
