# Generated by Django 5.0.6 on 2024-12-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_create_exams'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', through='exam.ExamQuestion', to='question.question'),
        ),
    ]
